name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Asegúrate de que coincide con tu proyecto

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      # Paso 7: Construir el proyecto
      - name: Build Project
        run: npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.aybecoconsultingperu.com
          username: capacitaciones@aybecoconsultingperu.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: dist/front-ay-b/browser/
          server-dir: .

      - name: Upload .htaccess
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.aybecoconsultingperu.com
          username: capacitaciones@aybecoconsultingperu.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: access/
          server-dir: . # Colocarlo en el directorio donde se requiere en el servidor
          dangerous-clean-slate: false
